export const SRI_LANKA_CITIES = [
  // Western Province
  "Colombo",
  "Dehiwala-Mount Lavinia",
  "Sri Jayawardenepura Kotte",
  "Moratuwa",
  "Negombo",
  "Kalutara",
  "Panadura",
  "Homagama",
  "Kaduwela",
  "Maharagama",
  "Kolonnawa",
  "Kesbewa",
  "Gampaha",
  "Ja-Ela",
  "Wattala",
  "Ragama",
  "Kandana",
  "Minuwangoda",
  "Divulapitiya",
  "Mirigama",
  "Beruwala",
  "Aluthgama",
  "Matugama",
  "Bandaragama",

  // Central Province
  "Kandy",
  "Matale",
  "Nuwara Eliya",
  "Gampola",
  "Nawalapitiya",
  "Dambulla",
  "Sigiriya",
  "Hatton",
  "Dikoya",
  "Talawakele",
  "Haputale",
  "Bandarawela",
  "Badulla",
  "Mahiyanganaya",
  "Moneragala",
  "Welimada",
  "Bibile",

  // Southern Province
  "Galle",
  "Matara",
  "Hambantota",
  "Weligama",
  "Unawatuna",
  "Hikkaduwa",
  "Ambalangoda",
  "Tangalle",
  "Tissamaharama",
  "Dickwella",
  "Koggala",
  "Mirissa",
  "Deniyaya",
  "Akuressa",
  "Elpitiya",

  // Northern Province
  "Jaffna",
  "Kilinochchi",
  "Mannar",
  "Vavuniya",
  "Mullaitivu",
  "Chavakachcheri",
  "Point Pedro",
  "Nelliady",
  "Kayts",

  // Eastern Province
  "Trincomalee",
  "Batticaloa",
  "Ampara",
  "Kalmunai",
  "Sammanthurai",
  "Akkaraipattu",
  "Kattankudy",
  "Valaichchenai",
  "Eravur",
  "Chenkaladi",

  // North Western Province
  "Kurunegala",
  "Puttalam",
  "Kuliyapitiya",
  "Narammala",
  "Wariyapola",
  "Chilaw",
  "Wennappuwa",
  "Marawila",
  "Nikaweratiya",
  "Maho",
  "Alawwa",
  "Pannala",
  "Nattandiya",

  // North Central Province
  "Anuradhapura",
  "Polonnaruwa",
  "Kekirawa",
  "Medawachchiya",
  "Tambuttegama",
  "Eppawala",
  "Mihintale",
  "Hingurakgoda",
  "Kaduruwela",
  "Medirigiriya",

  // Uva Province
  "Wellawaya",
  "Diyatalawa",
  "Passara",
  "Ella",
  "Hali-Ela",

  // Sabaragamuwa Province
  "Ratnapura",
  "Kegalle",
  "Balangoda",
  "Embilipitiya",
  "Avissawella",
  "Ruwanwella",
  "Mawanella",
  "Rambukkana",
  "Warakapola",
  "Eheliyagoda",
  "Kuruwita",
  "Kahawatta",
  "Pelmadulla",
];
